import type { Trade, Account, UserProfile } from "./types";
import { computeStats, fmtCurrency, fmtPct, groupBy, sum, tradePnl } from "./calc";

/**
 * Generate a plain-text shareable summary for copy/paste to mentors
 */
export const generateShareSummary = (
  trades: Trade[],
  account: Account,
  profile: UserProfile,
  dateRange?: { label: string }
): string => {
  const stats = computeStats(trades);
  const rangeLabel = dateRange?.label ?? "All Time";

  const bySetup = Object.entries(groupBy(trades, (t) => t.setup || "Untagged"))
    .map(([k, ts]) => {
      const pnls = ts.map(tradePnl);
      const wins = pnls.filter((p) => p > 0).length;
      return { name: k, trades: ts.length, winRate: ts.length ? (wins / ts.length) * 100 : 0, pnl: sum(pnls) };
    })
    .sort((a, b) => b.pnl - a.pnl);

  const lines: string[] = [
    `📊 YishaiEdge — Performance Summary`,
    `${"─".repeat(40)}`,
    `Trader: ${profile.displayName || "Trader"}`,
    `Account: ${account.name}`,
    `Period: ${rangeLabel}`,
    ``,
    `📈 KEY METRICS`,
    `  Trades: ${stats.trades}`,
    `  Win Rate: ${fmtPct(stats.winRate)} (${stats.wins}W / ${stats.losses}L / ${stats.breakeven}BE)`,
    `  Net P&L: ${fmtCurrency(stats.totalPnl, account.currency)}`,
    `  Profit Factor: ${isFinite(stats.profitFactor) ? stats.profitFactor.toFixed(2) + "x" : "∞"}`,
    `  Expectancy: ${fmtCurrency(stats.expectancy, account.currency)} / trade`,
    `  Avg Win: ${fmtCurrency(stats.avgWin, account.currency)}`,
    `  Avg Loss: ${fmtCurrency(stats.avgLoss, account.currency)}`,
    `  Avg R: ${stats.avgRR.toFixed(2)}R`,
    `  Best Streak: ${stats.bestStreak}W`,
    `  Worst Streak: ${stats.worstStreak}L`,
    `  Avg Hold: ${Math.round(stats.avgHoldMin)} min`,
    ``,
  ];

  if (bySetup.length > 0) {
    lines.push(`🎯 STRATEGY BREAKDOWN`);
    bySetup.forEach((s) => {
      const icon = s.pnl >= 0 ? "✅" : "❌";
      lines.push(`  ${icon} ${s.name}: ${s.trades} trades, ${fmtPct(s.winRate)} WR, ${fmtCurrency(s.pnl, account.currency)}`);
    });
    lines.push(``);
  }

  lines.push(`${"─".repeat(40)}`);
  lines.push(`Generated by YishaiEdge · yishaiedge.com`);

  return lines.join("\n");
};
